# Generated by Django 3.1.4 on 2020-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='amount')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('reason', models.CharField(max_length=150, verbose_name='reason')),
            ],
        ),
    ]
